### ISSUE TITLE
FIX: C string 0x0 character during unparse

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#69]
@penberg should we remove this line?
https://github.com/libtrading/libtrading/blob/master/lib/stringencoders/modp_numtoa.c#L300

**Comment by mstanichenko** [comment]
I am supposed to be involved here but do you think we can keep stringencoders part intact but rather modify our code (e.g. here https://github.com/libtrading/libtrading/blob/master/lib/proto/fix_message.c#L581). I was just thinking that modifying one function in the original library makes you modify all other functions as well (to have similar behavior). Eventually, you might diverge from the original version too far.
I believe at some point we might have our own dtoa implementation which might be event faster than modp_dtoa

**Comment by divaykin** [comment]
@mstanichenko @penberg thanks, I can copy the code of modp_numtoa if that helps. But is my understanding correct that we should not put zero here?

**Comment by mstanichenko** [comment]
Could you please elaborate what problem you are trying to solve? If you would like to introduce some micro-optimizations, then yes we probably don't have to spend any time putting zero byte in the end. Otherwise, I don't see any problem here as zero byte will be overwritten here https://github.com/libtrading/libtrading/blob/master/lib/proto/fix_message.c#L598

My previous comment was just a general note :)

**Comment by divaykin** [comment]
I see, I thought the zero would not be overwritten )

**Comment by divaykin** [comment]
Thanks again @mstanichenko
